trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: npm install
    displayName: "Install npm packages"

  - script: |
      touch .env.production

      printenv | grep '^REACT_APP_' >> .env.production || echo "No REACT_APP_ variables found."
    displayName: "Inject environment variables"

  - script: npm run build
    displayName: "Build react app"

  - task: ArchiveFiles@2
    displayName: "Zip build results"
    inputs:
      rootFolderOrFile: "$(Build.SourcesDirectory)/build"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactsStagingDirectory)/f2agent-fe-build.zip"
      replaceExistingArchive: true
      verbose: true
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactsStagingDirectory)"
      ArtifactName: f2agent-fe-build
