module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    extend: {
      colors: {
        lightBlue: "#687EFF",
        white: "#FFFFFF",
        black: "#000000",
        gray: "#F3F4F6",
        qweasd: "#123123",
        textSecondary: "#6B7280",
        emerald: "#10B981",
        "text-primary-light": "#111827",
        "text-primary-dark": "#000000",
        "text-secondary-light": "#6B7280",
        "text-secondary-dark": "#9CA3AF",
        "text-placeholder-light": "#9CA3AF",
        "text-placeholder-dark": "#6B7280",
        "text-disabled-light": "#9CA3AF",
        "text-disabled-dark": "#9CA3AF",
        "text-brand-light": "#687EFF",
        "text-brand-dark": "#687EFF",
        "text-error-light": "#EF4444",
        "text-error-dark": "#EF4444",
        "border-primary-light": "#D1D5DB",
        "border-primary-dark": "#6B7280",
        "border-brand-light": "#687EFF",
        "border-brand-dark": "#687EFF",
        "border-error-light": "#EF4444",
        "border-error-dark": "#EF4444",
        "border-disabled-light": "#E5E7EB",
        "border-disabled-dark": "#374151",
        "fg-primary-light": "#111827",
        "fg-primary-dark": "#000000",
        "fg-secondary-light": "#6B7280",
        "fg-secondary-dark": "#E5E7EB",
        "fg-tertiary-light": "#9CA3AF",
        "fg-tertiary-dark": "#9CA3AF",
        "fg-brand-light": "#687EFF",
        "fg-brand-dark": "#687EFF",
        "fg-error-light": "#EF4444",
        "fg-error-dark": "#EF4444",
        "fg-disabled-light": "#9CA3AF",
        "fg-disabled-dark": "#9CA3AF",
        "bg-primary-light": "#000000",
        "bg-primary-dark": "#111827",
        "bg-primary-solid-light": "#1F2937",
        "bg-primary-solid-dark": "#1F2937",
        "bg-secondary-light": "#F3F4F6",
        "bg-secondary-dark": "#374151",
        "bg-brand-contrast-light": "#687EFF",
        "bg-brand-contrast-dark": "#687EFF",
        "bg-brand-conrast-hover-light": "#485CD5",
        "bg-brand-conrast-hover-dark": "#8691FF",
        "bg-brand-secondary-light": "#A2A6FF",
        "bg-brand-secondary-dark": "#8691FF",
        "bg-brand-tertiary-light": "#E9E8FF",
        "bg-brand-tertiary-dark": "#1F2937",
        "bg-active-light": "#F3F4F6",
        "bg-active-dark": "#374151",
        "bg-brand-disabled-primary-light": "#D2D2FF",
        "bg-brand-disabled-primary-dark": "#3A47AA",
        "bg-brand-disabled-secondary-light": "#A2A6FF",
        "bg-brand-disabled-secondary-dark": "#A2A6FF",
        "bg-disabled-primary-light": "#F3F4F6",
        "bg-disabled-primary-dark": "#374151",
        "bg-disabled-secondary-light": "#E5E7EB",
        "bg-disabled-secondary-dark": "#4B5563",
        "bg-error-primary-light": "#EF4444",
        "bg-error-primary-dark": "#EF4444",
        "bg-error-primary-hover-light": "#DC2626",
        "bg-error-primary-hover-dark": "#F87171",
        "bg-error-secondary-light": "#FEF2F2",
        "bg-error-secondary-dark": "#450A0A",
      },
      fontSize: {
        "9xl": "128px",
        "8xl": "96px",
        "7xl": "72px",
        "6xl": "60px",
        "5xl": "48px",
        "4xl": "36px",
        "3xl": "30px",
        "2xl": "24px",
        xl: "20px",
        lg: "18px",
        md: "16px",
        sm: "14px",
        xs: "12px",
      },
      fontWeight: {
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      animation: {
        pulse: "pulse 1.5s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
    screens: {
      xs: "220px",
      "xs-chat": "610px",
      sm: "500px",
      "sm-chat": "890px",
      md: "780px",
      "md-chat": "1170px",
      lg: "1060px",
      "lg-chat": "1450px",
      xl: "1340px",
      "xl-chat": "1730px",

      "max-content-with-nav-bp": "1656px",
      "max-content-with-chat-bp": "1870px",
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
