enum RoutingPath {
  DefaultPage = "/",
  PrivacyPage = "/privacy-policy",
  InvoicePage = "/invoice",
  HelpdeskPage = "/helpdesk",
  PatientRegistration = "/patient-registration",
  EcommercePage = "/ecommerce",
  KitchenViewPage = "/kitchen",
  CustomerFilterPage = "/customer-filter",
  ScheduleDemoPage = "/schedule-demo",
  FrontdeskPage = "/frontdesk",
  CheckInPage = "/checkin",
  AddDeal = "/add-deal",
  MerchantRegistration = "/merchant-registration",
  AddProduct = "/add-product",
  CarAccidentPage = "/car-accident",
  HouseInspectionPage = "/room-inspection",
  TravelReimbursementPage = "/travel-reimbursement",
  SurgeryClaimPage = "/surgery-claim",
  SpeechAssessmentPage = "/speech-assessment",
  NoSurgeryClaimPage = "/no-surgery-claim",
  PatientLookupPage = "/patient-lookup",
}

export default RoutingPath;
