const MAX_CONTENT_WIDTH = 1096;
const LAPTOP_WIDTH = 1024;
const TABLET_WIDTH = 780;
const HIDE_CONTENT_BP = 720; // highest min content width w/padding + side nav
const IPAD_LABEL_SHOW = 780;
const IPAD_LABEL_HIDE = 1380;

export { MAX_CONTENT_WIDTH, LAPTOP_WIDTH, TABLET_WIDTH, HIDE_CONTENT_BP, IPAD_LABEL_SHOW, IPAD_LABEL_HIDE };
