import RoutingPath from "../routes/routes";
import {
  MedicalInformationOutlined,
  HomeOutlined,
  HelpOutline,
  ArticleOutlined,
  Home,
  Article,
  MedicalInformation,
  Help,
  KitchenOutlined,
  PeopleAltOutlined,
  ListAltOutlined,
  CalendarTodayOutlined,
  CoffeeOutlined,
  EventAvailableOutlined,
  HandshakeOutlined,
  StorefrontOutlined,
  PlusOneOutlined,
  MinorCrashOutlined,
  ApartmentOutlined,
  FlightOutlined,
  LocalHospitalOutlined,
  RecordVoiceOverOutlined,
  Person2Outlined,
} from "@mui/icons-material";
import { envToBool } from "../helpers/env-helper";
export const NAV_DRAWER_WIDTH = 280;

export const SIDE_NAV_LINKS = [
  {
    path: RoutingPath.DefaultPage,
    icon: HomeOutlined,
    icon_dark: Home,
    text: "Home",
    isHidden: true,
  },
  {
    path: RoutingPath.InvoicePage,
    icon: ArticleOutlined,
    icon_dark: Article,
    text: "Invoices",
    buttonTitle: "Add invoice",
    description: "Quickly add a new invoice to the system.",
  },
  {
    path: RoutingPath.PatientRegistration,
    icon: MedicalInformationOutlined,
    icon_dark: MedicalInformation,
    text: "Patient Registration",
    description: "Register a new patient and their details.",
    buttonTitle: "Register patient",
  },
  {
    path: RoutingPath.HelpdeskPage,
    icon: HelpOutline,
    icon_dark: Help,
    text: "Help Desk",
    buttonTitle: "Helpdesk",
    description: "Get assistance or report an issue.",
  },
  {
    path: RoutingPath.EcommercePage,
    icon: ListAltOutlined,
    icon_dar: ListAltOutlined,
    text: "Orders",
    buttonTitle: "Update orders",
    description: "Make changes to existing orders.",
  },
  {
    path: RoutingPath.KitchenViewPage,
    icon: KitchenOutlined,
    icon_dar: KitchenOutlined,
    text: "Kitchen",
    buttonTitle: "Kitchen View",
    description: "Simulate kitchen view.",
  },
  {
    path: RoutingPath.CustomerFilterPage,
    icon: PeopleAltOutlined,
    icon_dar: PeopleAltOutlined,
    text: "Customer Filter",
    description: "Get customer order details, search, and filter orders.",
    buttonTitle: "Customer Filter",
  },
  {
    path: RoutingPath.FrontdeskPage,
    icon: CoffeeOutlined,
    icon_dar: CoffeeOutlined,
    text: "Coffee Shop",
    isDisabled: envToBool(process.env.REACT_APP_IS_FRONTDESK_DISABLED),
    description: "Check out coffee shop frontdesk.",
    buttonTitle: "Front Desk",
  },
  {
    path: RoutingPath.ScheduleDemoPage,
    icon: CalendarTodayOutlined,
    icon_dar: CalendarTodayOutlined,
    text: "Schedule a Demo",
    buttonTitle: "Schedule a Demo",
    description: "Scheduling a demo by automating the process.",
    isDisabled: envToBool(process.env.REACT_APP_IS_SCHEDULE_DISABLED),
  },
  {
    path: RoutingPath.CheckInPage,
    icon: EventAvailableOutlined,
    icon_dar: EventAvailableOutlined,
    text: "Check In",
    isDisabled: envToBool(process.env.REACT_APP_IS_CHECKIN_DISABLED),
    description: "Checking in a new hotel resident.",
    buttonTitle: "Try Check-in",
  },
  {
    path: RoutingPath.AddDeal,
    icon: HandshakeOutlined,
    icon_dar: HandshakeOutlined,
    isDisabled: envToBool(process.env.REACT_APP_IS_DEAL_DISABLED),
    text: "Add Deal",
    description: "Create new deals.",
    buttonTitle: "Add Deal",
  },
  {
    path: RoutingPath.MerchantRegistration,
    icon: StorefrontOutlined,
    icon_dark: StorefrontOutlined,
    text: "Merchant Registration",
    isDisabled: envToBool(process.env.REACT_APP_IS_MERCHANT_DISABLED),
    description: "Multi-step merchant registration.",
    buttonTitle: "Merchant",
  },
  {
    path: RoutingPath.AddProduct,
    icon: PlusOneOutlined,
    icon_dark: PlusOneOutlined,
    text: "Add Product",
    buttonTitle: "Add Product",
    description: "Add product to registry.",
    isDisabled: envToBool(process.env.REACT_APP_IS_ADDPRODUCT_DISABLED),
  },
  {
    path: RoutingPath.CarAccidentPage,
    icon: MinorCrashOutlined,
    icon_dar: MinorCrashOutlined,
    text: "Car Accident Report",
    description: "Submit report.",
    buttonTitle: "Accident Report",
    isDisabled: envToBool(process.env.REACT_APP_IS_ACCIDENT_DISABLED),
  },
  {
    path: RoutingPath.HouseInspectionPage,
    icon: ApartmentOutlined,
    icon_dar: ApartmentOutlined,
    text: "House Inspection",
    description: "Submit house inspection report.",
    buttonTitle: "House Report",
    isDisabled: envToBool(process.env.REACT_APP_IS_APPARTMENT_DISABLED),
  },
  {
    path: RoutingPath.TravelReimbursementPage,
    icon: FlightOutlined,
    icon_dar: FlightOutlined,
    text: "Travel Reimbursement",
    description: "Submit travel reimbursement report.",
    buttonTitle: "Refund Travel",
    isDisabled: envToBool(process.env.REACT_APP_IS_TRAVEL_DISABLED),
  },
  {
    path: RoutingPath.SurgeryClaimPage,
    icon: LocalHospitalOutlined,
    icon_dar: LocalHospitalOutlined,
    text: "Surgery Claim",
    description: "Submit surgery claim report.",
    buttonTitle: "Surgery Claim",
    isDisabled: envToBool(process.env.REACT_APP_IS_SURGERY_CLAIM_DISABLED),
  },
  {
    path: RoutingPath.SpeechAssessmentPage,
    icon: RecordVoiceOverOutlined,
    icon_dar: RecordVoiceOverOutlined,
    text: "Speech Assessment",
    description: "Submit speech assessment report.",
    buttonTitle: "Speech Assessment",
    isDisabled: envToBool(process.env.REACT_APP_IS_SPEECH_ASSESSMENT_DISABLED),
  },
  {
    path: RoutingPath.NoSurgeryClaimPage,
    icon: Person2Outlined,
    icon_dar: Person2Outlined,
    text: "Treatment Claim",
    description: "Submit non-surgical treatment claim report.",
    buttonTitle: "Claim",
    isDisabled: envToBool(process.env.REACT_APP_IS_NO_SURGERY_CLAIM_DISABLED),
  },
];
